[ {
    "AccessionNumber" : "0000021344-14-000008", 
    "EntityRegistrantName" : "COCA COLA CO", 
    "CIK" : "http://www.sec.gov/CIK 0000021344", 
    "FiscalYear" : 2013, 
    "FiscalPeriod" : "FY", 
    "AcceptanceDatetime" : "2014-02-27T13:24:23Z", 
    "FormType" : "10-K", 
    "Components" : [ {
      "NetworkLabel" : "0001000 - Document - Document and Entity Information Document", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/DocumentAndEntityInformationDocument", 
      "Category" : "Document", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "DocumentAndEntityInformation", 
      "ReportElements" : 19, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 14, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "1001000 - Statement - CONSOLIDATED STATEMENTS OF INCOME", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfIncomeCalc2", 
      "Category" : "Statement", 
      "SubCategory" : "Unknown", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeStatement", 
      "ReportElements" : 0, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 0, 
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "1001000 - Statement - CONSOLIDATED STATEMENTS OF INCOME", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfIncome", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeStatement", 
      "ReportElements" : 25, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 20, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "1002000 - Statement - CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfComprehensiveIncomeCalc2", 
      "Category" : "Statement", 
      "SubCategory" : "Unknown", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "StatementOfComprehensiveIncome", 
      "ReportElements" : 0, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 0, 
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "1002000 - Statement - CONSOLIDATED STATEMENTS OF COMPREHENSIVE INCOME", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfComprehensiveIncome", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "StatementOfComprehensiveIncome", 
      "ReportElements" : 14, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 8, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "1003000 - Statement - CONSOLIDATED BALANCE SHEETS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedBalanceSheets", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BalanceSheet", 
      "ReportElements" : 46, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 36, 
      "Abstracts" : 7
    }, {
      "NetworkLabel" : "1003500 - Statement - CONSOLIDATED BALANCE SHEET (Parentheticals)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedBalanceSheetParentheticals", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BalanceSheetParenthetical", 
      "ReportElements" : 12, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 2, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "1004000 - Statement - CONSOLIDATED STATEMENTS OF CASH FLOWS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfCashFlows", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "CashFlowStatement", 
      "ReportElements" : 38, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 29, 
      "Abstracts" : 6
    }, {
      "NetworkLabel" : "1005000 - Statement - CONSOLIDATED STATEMENTS OF SHAREOWNERS' EQUITY", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfShareownersEquity", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "StatementOfChangesInEquity", 
      "ReportElements" : 34, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 8, 
      "LineItems" : 1, 
      "Concepts" : 21, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "1005500 - Statement - CONSOLIDATED STATEMENTS OF SHAREOWNERS' EQUITY (Parentheticals)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ConsolidatedStatementsOfShareownersEquityParentheticals", 
      "Category" : "Statement", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "StatementOfChangesInEquityParenthetical", 
      "ReportElements" : 18, 
      "Tables" : 1, 
      "Axis" : 7, 
      "Members" : 7, 
      "LineItems" : 1, 
      "Concepts" : 1, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2101100 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPolicies", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2102100 - Disclosure - ACQUISITIONS AND DIVESTITURES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AcquisitionsAndDivestitures", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BusinessCombinationDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2103100 - Disclosure - INVESTMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/Investments", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2104100 - Disclosure - INVENTORIES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/Inventories", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "InventoryDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2105100 - Disclosure - HEDGING TRANSACTIONS AND DERIVATIVE FINANCIAL INSTRUMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstruments", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2106100 - Disclosure - EQUITY METHOD INVESTMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/EquityMethodInvestments", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2107100 - Disclosure - PROPERTY, PLANT AND EQUIPMENT", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PropertyPlantAndEquipment", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PropertyPlantAndEquipmentDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2108100 - Disclosure - INTANGIBLE ASSETS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IntangibleAssets", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IntangibleAssetsAndGoodwill", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2109100 - Disclosure - ACCOUNTS PAYABLE AND ACCRUED EXPENSES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AccountsPayableAndAccruedExpenses", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "AccountsPayableAndAccruedLiabilitiesDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2110100 - Disclosure - DEBT AND BORROWING ARRANGEMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/DebtAndBorrowingArrangements", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "DebtDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2111100 - Disclosure - COMMITMENTS AND CONTINGENCIES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/CommitmentsAndContingencies", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "ContingenciesDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2112100 - Disclosure - STOCK COMPENSATION PLANS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/StockCompensationPlans", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2113100 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlans", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2114100 - Disclosure - INCOME TAXES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IncomeTaxes", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeTaxDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2115100 - Disclosure - OTHER COMPREHENSIVE INCOME", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OtherComprehensiveIncome", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2116100 - Disclosure - FAIR VALUE MEASUREMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurements", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2117100 - Disclosure - SIGNIFICANT OPERATING AND NONOPERATING ITEMS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/SignificantOperatingAndNonoperatingItems", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2118100 - Disclosure - PRODUCTIVITY, INTEGRATION AND RESTRUCTURING INITIATIVES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ProductivityIntegrationAndRestructuringInitiatives", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2119100 - Disclosure - OPERATING SEGMENTS", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OperatingSegments", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 6, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 1, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2120100 - Disclosure - NET CHANGE IN OPERATING ASSETS AND LIABILITIES", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/NetChangeInOperatingAssetsAndLiabilities", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2122100 - Disclosure - SUBSEQUENT EVENT", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/SubsequentEvent", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SubsequentEvents", 
      "ReportElements" : 6, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 1, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2201201 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Policies)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesPolicies", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 21, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 20, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2301302 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2302301 - Disclosure - ACQUISITIONS AND DIVESTITURES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AcquisitionsAndDivestituresTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BusinessCombinationDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2303301 - Disclosure - INVESTMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 6, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 5, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2304301 - Disclosure - INVENTORIES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InventoriesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "InventoryDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2305301 - Disclosure - HEDGING TRANSACTIONS AND DERIVATIVE FINANCIAL INSTRUMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 7, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 6, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2306301 - Disclosure - EQUITY METHOD INVESTMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/EquityMethodInvestmentsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2307301 - Disclosure - PROPERTY, PLANT AND EQUIPMENT (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PropertyPlantAndEquipmentTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PropertyPlantAndEquipmentDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2308301 - Disclosure - INTANGIBLE ASSETS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IntangibleAssetsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IntangibleAssetsAndGoodwill", 
      "ReportElements" : 5, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 4, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2309301 - Disclosure - ACCOUNTS PAYABLE AND ACCRUED EXPENSES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AccountsPayableAndAccruedExpensesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "AccountsPayableAndAccruedLiabilitiesDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2310301 - Disclosure - DEBT AND BORROWING ARRANGEMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/DebtAndBorrowingArrangementsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "DebtDisclosure", 
      "ReportElements" : 3, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 2, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2311301 - Disclosure - COMMITMENTS AND CONTINGENCIES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/CommitmentsAndContingenciesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "ContingenciesDisclosure", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2312301 - Disclosure - STOCK COMPENSATION PLANS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/StockCompensationPlansTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 5, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 4, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2313301 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 14, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 13, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2314301 - Disclosure - INCOME TAXES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IncomeTaxesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeTaxDisclosure", 
      "ReportElements" : 7, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 6, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2315301 - Disclosure - OTHER COMPREHENSIVE INCOME (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OtherComprehensiveIncomeTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 5, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 4, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2316301 - Disclosure - FAIR VALUE MEASUREMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurementsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 12, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 2, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2318301 - Disclosure - PRODUCTIVITY, INTEGRATION AND RESTRUCTURING INITIATIVES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ProductivityIntegrationAndRestructuringInitiativesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2319301 - Disclosure - OPERATING SEGMENTS (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OperatingSegmentsTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 8, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 3, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2320301 - Disclosure - NET CHANGE IN OPERATING ASSETS AND LIABILITIES (Tables)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/NetChangeInOperatingAssetsAndLiabilitiesTables", 
      "Category" : "Disclosure", 
      "SubCategory" : "TextBlockLevel1To3", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 2, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 1, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2401403 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 35, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 5, 
      "LineItems" : 1, 
      "Concepts" : 24, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2401404 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 8, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 3, 
      "LineItems" : 1, 
      "Concepts" : 1, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2401405 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Details 3)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesDetails3", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 11, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 2, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2401406 - Disclosure - BUSINESS AND SUMMARY OF SIGNIFICANT ACCOUNTING POLICIES (Details 4)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/BusinessAndSummaryOfSignificantAccountingPoliciesDetails4", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SignificantAccountingPolicies", 
      "ReportElements" : 17, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 5, 
      "LineItems" : 1, 
      "Concepts" : 6, 
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2402402 - Disclosure - ACQUISITIONS AND DIVESTITURES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AcquisitionsAndDivestituresDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BusinessCombinationDisclosure", 
      "ReportElements" : 28, 
      "Tables" : 1, 
      "Axis" : 5, 
      "Members" : 12, 
      "LineItems" : 1, 
      "Concepts" : 8, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2402403 - Disclosure - ACQUISITIONS AND DIVESTITURES (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AcquisitionsAndDivestituresDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "BusinessCombinationDisclosure", 
      "ReportElements" : 34, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 6, 
      "LineItems" : 1, 
      "Concepts" : 23, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2403402 - Disclosure - INVESTMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 10, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2403403 - Disclosure - INVESTMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 11, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 3, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2403404 - Disclosure - INVESTMENTS (Details 3)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails3", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 15, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 4, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403405 - Disclosure - INVESTMENTS (Details 4)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails4", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 11, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 2, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2403406 - Disclosure - INVESTMENTS (Details 5)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails5", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 9, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 8, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2403407 - Disclosure - INVESTMENTS (Details 6)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InvestmentsDetails6", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 3, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 2, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2404402 - Disclosure - INVENTORIES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/InventoriesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "InventoryDisclosure", 
      "ReportElements" : 6, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 4, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2405402 - Disclosure - HEDGING TRANSACTIONS AND DERIVATIVE FINANCIAL INSTRUMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 34, 
      "Tables" : 1, 
      "Axis" : 4, 
      "Members" : 19, 
      "LineItems" : 1, 
      "Concepts" : 8, 
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2405403 - Disclosure - HEDGING TRANSACTIONS AND DERIVATIVE FINANCIAL INSTRUMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/HedgingTransactionsAndDerivativeFinancialInstrumentsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 29, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 19, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2406402 - Disclosure - EQUITY METHOD INVESTMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/EquityMethodInvestmentsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 40, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 8, 
      "LineItems" : 1, 
      "Concepts" : 23, 
      "Abstracts" : 5
    }, {
      "NetworkLabel" : "2406403 - Disclosure - EQUITY METHOD INVESTMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/EquityMethodInvestmentsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 17, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 5, 
      "LineItems" : 1, 
      "Concepts" : 7, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2407402 - Disclosure - PROPERTY, PLANT AND EQUIPMENT (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PropertyPlantAndEquipmentDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PropertyPlantAndEquipmentDisclosure", 
      "ReportElements" : 12, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 5, 
      "LineItems" : 1, 
      "Concepts" : 3, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2408402 - Disclosure - INTANGIBLE ASSETS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IntangibleAssetsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IntangibleAssetsAndGoodwill", 
      "ReportElements" : 29, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 8, 
      "LineItems" : 1, 
      "Concepts" : 13, 
      "Abstracts" : 4
    }, {
      "NetworkLabel" : "2408403 - Disclosure - INTANGIBLE ASSETS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IntangibleAssetsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IntangibleAssetsAndGoodwill", 
      "ReportElements" : 18, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 7, 
      "LineItems" : 1, 
      "Concepts" : 6, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2409402 - Disclosure - ACCOUNTS PAYABLE AND ACCRUED EXPENSES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/AccountsPayableAndAccruedExpensesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "AccountsPayableAndAccruedLiabilitiesDisclosure", 
      "ReportElements" : 8, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 7, 
      "Abstracts" : 1
    }, {
      "NetworkLabel" : "2410402 - Disclosure - DEBT AND BORROWING ARRANGEMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/DebtAndBorrowingArrangementsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "DebtDisclosure", 
      "ReportElements" : 11, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 1, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2410403 - Disclosure - DEBT AND BORROWING ARRANGEMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/DebtAndBorrowingArrangementsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "DebtDisclosure", 
      "ReportElements" : 69, 
      "Tables" : 1, 
      "Axis" : 5, 
      "Members" : 33, 
      "LineItems" : 1, 
      "Concepts" : 26, 
      "Abstracts" : 4
    }, {
      "NetworkLabel" : "2411402 - Disclosure - COMMITMENTS AND CONTINGENCIES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/CommitmentsAndContingenciesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "ContingenciesDisclosure", 
      "ReportElements" : 42, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 8, 
      "LineItems" : 1, 
      "Concepts" : 23, 
      "Abstracts" : 7
    }, {
      "NetworkLabel" : "2412402 - Disclosure - STOCK COMPENSATION PLANS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/StockCompensationPlansDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 85, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 19, 
      "LineItems" : 1, 
      "Concepts" : 57, 
      "Abstracts" : 5
    }, {
      "NetworkLabel" : "2413402 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 47, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 6, 
      "LineItems" : 1, 
      "Concepts" : 32, 
      "Abstracts" : 7
    }, {
      "NetworkLabel" : "2413403 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 21, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 15, 
      "LineItems" : 1, 
      "Concepts" : 2, 
      "Abstracts" : 0
    }, {
      "NetworkLabel" : "2413404 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details 3)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails3", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 28, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 14, 
      "LineItems" : 1, 
      "Concepts" : 8, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2413405 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details 4)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails4", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 41, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 4, 
      "LineItems" : 1, 
      "Concepts" : 29, 
      "Abstracts" : 6
    }, {
      "NetworkLabel" : "2413406 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details 5)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails5", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 25, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 6, 
      "LineItems" : 1, 
      "Concepts" : 12, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2413407 - Disclosure - PENSION AND OTHER POSTRETIREMENT BENEFIT PLANS (Details 6)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/PensionAndOtherPostretirementBenefitPlansDetails6", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "PostemploymentBenefits", 
      "ReportElements" : 20, 
      "Tables" : 1, 
      "Axis" : 4, 
      "Members" : 8, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2414402 - Disclosure - INCOME TAXES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IncomeTaxesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeTaxDisclosure", 
      "ReportElements" : 71, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 4, 
      "LineItems" : 1, 
      "Concepts" : 59, 
      "Abstracts" : 5
    }, {
      "NetworkLabel" : "2414403 - Disclosure - INCOME TAXES (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IncomeTaxesDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeTaxDisclosure", 
      "ReportElements" : 37, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 3, 
      "LineItems" : 1, 
      "Concepts" : 26, 
      "Abstracts" : 5
    }, {
      "NetworkLabel" : "2414404 - Disclosure - INCOME TAXES (Details 3)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/IncomeTaxesDetails3", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "IncomeTaxDisclosure", 
      "ReportElements" : 12, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 2, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 3
    }, {
      "NetworkLabel" : "2415402 - Disclosure - OTHER COMPREHENSIVE INCOME (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OtherComprehensiveIncomeDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 85, 
      "Tables" : 1, 
      "Axis" : 3, 
      "Members" : 16, 
      "LineItems" : 1, 
      "Concepts" : 47, 
      "Abstracts" : 18
    }, {
      "NetworkLabel" : "2416402 - Disclosure - FAIR VALUE MEASUREMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurementsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 24, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 11, 
      "LineItems" : 1, 
      "Concepts" : 6, 
      "Abstracts" : 4
    }, {
      "NetworkLabel" : "2416403 - Disclosure - FAIR VALUE MEASUREMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurementsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 38, 
      "Tables" : 1, 
      "Axis" : 7, 
      "Members" : 19, 
      "LineItems" : 1, 
      "Concepts" : 9, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2416404 - Disclosure - FAIR VALUE MEASUREMENTS (Details 3)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurementsDetails3", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 38, 
      "Tables" : 1, 
      "Axis" : 5, 
      "Members" : 21, 
      "LineItems" : 1, 
      "Concepts" : 7, 
      "Abstracts" : 4
    }, {
      "NetworkLabel" : "2416405 - Disclosure - FAIR VALUE MEASUREMENTS FAIR VALUE MEASUREMENTS (Details 4)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/FairValueMeasurementsFairValueMeasurementsDetails4", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "FairValueMeasurementsOther", 
      "ReportElements" : 10, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 3, 
      "LineItems" : 1, 
      "Concepts" : 2, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2417401 - Disclosure - SIGNIFICANT OPERATING AND NONOPERATING ITEMS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/SignificantOperatingAndNonoperatingItemsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 68, 
      "Tables" : 1, 
      "Axis" : 7, 
      "Members" : 30, 
      "LineItems" : 1, 
      "Concepts" : 23, 
      "Abstracts" : 7
    }, {
      "NetworkLabel" : "2418402 - Disclosure - PRODUCTIVITY, INTEGRATION AND RESTRUCTURING INITIATIVES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/ProductivityIntegrationAndRestructuringInitiativesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 22, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 10, 
      "LineItems" : 1, 
      "Concepts" : 7, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2419402 - Disclosure - OPERATING SEGMENTS (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OperatingSegmentsDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 12, 
      "Tables" : 1, 
      "Axis" : 1, 
      "Members" : 3, 
      "LineItems" : 1, 
      "Concepts" : 5, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2419403 - Disclosure - OPERATING SEGMENTS (Details 2)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/OperatingSegmentsDetails2", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 79, 
      "Tables" : 1, 
      "Axis" : 9, 
      "Members" : 32, 
      "LineItems" : 1, 
      "Concepts" : 34, 
      "Abstracts" : -1
    }, {
      "NetworkLabel" : "2420402 - Disclosure - NET CHANGE IN OPERATING ASSETS AND LIABILITIES (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/NetChangeInOperatingAssetsAndLiabilitiesDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "UncategorizedInformation", 
      "ReportElements" : 9, 
      "Tables" : 0, 
      "Axis" : 0, 
      "Members" : 0, 
      "LineItems" : 0, 
      "Concepts" : 7, 
      "Abstracts" : 2
    }, {
      "NetworkLabel" : "2422401 - Disclosure - SUBSEQUENT EVENT SUBSEQUENT EVENT (Details)", 
      "NetworkIdentifier" : "http://www.thecocacolacompany.com/role/SubsequentEventSubsequentEventDetails", 
      "Category" : "Disclosure", 
      "SubCategory" : "Detail", 
      "Table" : "xbrl28:ImpliedTable", 
      "Disclosure" : "SubsequentEvents", 
      "ReportElements" : 13, 
      "Tables" : 1, 
      "Axis" : 2, 
      "Members" : 4, 
      "LineItems" : 1, 
      "Concepts" : 4, 
      "Abstracts" : 2
    } ]
  } ]
